import type { Metadata } from "next";
import { Providers } from "@/context/Providers";
import HomeNav from "../components/HomeNav";

export const metadata: Metadata = {
  title: "portfolio-0-nextjs-supabase",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <HomeNav />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
